### PR TITLE
updates for gazebo

### PR DESCRIPTION
**Pull request by SteveMacenski**
updates on the master branch for the urdf viewing and simulation in gazebo. Note: moment of inertia and masses were chosen for stability in simulation and do not represent the true masses of the robot.

### CODE REVIEW

**Comment by GertKanter** [comment]
Hi, Steve!

This is great! One thing, though: can you make the changes in .xacro instead and then generate the .urdf? For example, you can use the "generate_urdf.launch" from launch directory. This is because the .urdf is automatically generated from .xacro files and the manual changes will be lost if we regenerate from .xacro later.

**Comment by SteveMacenski** [comment]
Hi!

I'm not sure how to edit the .xacro file to be robust. Though it appears that all of the prefixes are blank in the xacro anyhow, so the urdf and urdf.xacro are identical.

**Comment by GertKanter** [comment]
It is quite straightforward: just put the inertials in the link definitions (You can just copy-paste these in the right places, it seems) and then add the transmission definitions in the corresponding places in .xacro, but here you should use the ${prefix} for every name. The main benefit of this xacro approach is that you can generate multi-manipulator setups more easily - for example, my robot has two manipulators so they have "left_" and "right_" prefixes so that there is no name collision in the final robot .urdf.

In the repository, I have left them as empty because everyone can prefix their setup however they like.

**Comment by GertKanter** [comment]
Hi, Steve!

I haven't heard back from you about the fix. Are you working on the .xacro or planning to work on it?

**Comment by SteveMacenski** [comment]
Hi! I plan to. Semester restarted and blanked on it. I will make my first draft of it this week. Hopefully its pretty straight forward from the URDF.

**Comment by SteveMacenski** [comment]
Hi, I have updated the xacro. The only missing feature is the transmissions which are not required except when in ROS hydro. If in indigo, it should work.

**Comment by GertKanter** [comment]
Looks good! Thanks for the contribution!

**Pull request merged**
